quiz/urls.py
from django.urls import path
from .views import (
    QuestionList,
    loginView,
    # play_quiz,
    PlayQuizView,
    Leaderboard,
    submission_Result,
    Profile,
    signupView,
    verify_email,
    category_list,
    MessageDetail,
    MessageList,
    AnnouncementDetail,
    AnnouncementList,
    CreateMessage,
    EditProfile,
    create_question,
    DeleteMessage,
    SearchResultListView,
    quiz_results,
    results,
    quiz_analytics,
    quiz_taken,
    quiz_created
)
app_name = "quiz"


urlpatterns = [
    # ===============================
    # Both Unauthenticated Users
    # ===============================
    path('leaderboard/', Leaderboard.as_view(), name='leaderboard'),
    path('login/', loginView, name='login'),
    path('signup/', signupView, name='signup'),
    path('verify-email/', verify_email, name="verify_email"),

    # ===============================
    # Authenticated Users Only
    # ===============================
    path('quiz', QuestionList.as_view(), name="question_list"),
    path('quiz_taken', quiz_taken, name="quiz_taken"),
    path('quiz_created', quiz_created, name="quiz_created"),
    path('play-quiz/<int:category_id>/', PlayQuizView.as_view(), name='play'),
    path('quiz/new/', create_question, name="quiz_new"),
    path('analytics/', quiz_analytics, name="quiz_analytics"),
    path('quiz-results/', quiz_results, name="quiz_results"),
    path('results/<int:category_id>/', results, name='results'),
    path('category/', category_list, name="category"),
    path('search/', SearchResultListView.as_view(), name="search_result"),
    path('submission_result/', submission_Result, name='submission_result'),
    path('profile/', Profile.as_view(), name="profile"),
    path('profile-edit/<int:pk>/', EditProfile.as_view(), name="edit_profile"),
    path('messages/', MessageList.as_view(), name="messages"),
    path('messages/new/', CreateMessage.as_view(), name="messages_new"),
    path('messages/<uuid:pk>/', MessageDetail.as_view(), name="message_detail"),
    path('messages/delete/<uuid:pk>/',
         DeleteMessage.as_view(), name="message_delete"),
    path('announcement/', AnnouncementList.as_view(), name="announcements"),
    path('announcement/<uuid:pk>/', AnnouncementDetail.as_view(),
         name="announcement_detail"),

]

quizApp_Config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from quiz import views as quiz_views
from django.conf.urls import handler404, handler500, handler403

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quiz.urls')),
    path('', include('quiz.urls', namespace='quiz')),
    path('', include('pages.urls')),
    path('', include('allauth.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = quiz_views.error404
handler500 = quiz_views.error_500

templates/profile/edit-profile.html
{% extends '_base.html' %}
{% load static %}
{% block title %}Edit Profile{% endblock title %}

{% block style %}
<link rel="stylesheet" href="{% static 'assets/css/profile.css' %}">
{% endblock style %}

{% block content %}
<main>
    <div class="container">
        <div class="text-section">
            <div class="top-content">
                <h4>Quizzer</h4>
            </div>
            <div class="box-content">
                <h2>Edit Your Profile</h2>
                <p>Make your account up to date</p>
                <a href="{% url 'account_change_password' %}">Change Password</a>
            </div>
        </div>
        <div class="form-section">
            <form action="" method="post">
                {% csrf_token %}
                <div class="form-heading">
                    <h1>Edit Profile</h1>
                </div>

                {{ form.as_p }}
                <input type="submit" value="Update">
            </form>
        </div>
    </div>
</main>
{% endblock content %}

templates/profile/profile.html
{% extends '_base.html' %}
{% load static %}
{% block title %}Profile{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'assets/css/profile.css' %}">
{% endblock style %}

{% block content %}
<main>
    <div class="container">
        <div class="text-section">
            <div class="top-content">
                <h4>Quizzer</h4>
            </div>
            <div class="box-content">
                <h2>Edit Your Profile</h2>
                <p>Make your account up to date</p>
                <a href="{% url 'account_change_password' %}">Change Password</a>
            </div>
        </div>

        <div class="form-section">
            <div class="profile-details">
                <div class="group">
                    <i class="">F</i>
                    <p>{{ request.user.first_name }}</p>
                </div>

                <div class="group">
                    <i class="">L</i>
                    <p>{{ request.user.last_name}}</p>
                </div>

                <div class="group">
                    <i class="bi bi-person-fill"></i>
                    <p>{{ request.user.username}}</p>
                </div>
                ,
                <div class="group">
                    <i class="bi bi-envelope-fill"></i>
                    <p>{{ request.user.email }}</p>
                </div>

                <div class="group">
                    <i class="">G</i>
                    <p>{{ request.user.gender }}</p>
                </div>

                <a href="{% url 'quiz:edit_profile' request.user.id %}" class="edit_account_link">Edit Profile</a>
            </div>
        </div>
    </div>
</main>
{% endblock content %}