quiz/urls.py
from django.urls import path
from .views import (
    QuestionList,
    loginView,
    # play_quiz,
    PlayQuizView,
    Leaderboard,
    submission_Result,
    Profile,
    signupView,
    verify_email,
    category_list,
    MessageDetail,
    MessageList,
    AnnouncementDetail,
    AnnouncementList,
    CreateMessage,
    EditProfile,
    create_question,
    DeleteMessage,
    SearchResultListView,
    quiz_results,
    results,
    quiz_analytics,
    quiz_taken,
    quiz_created
)
app_name = "quiz"


urlpatterns = [
    # ===============================
    # Both Unauthenticated Users
    # ===============================
    path('leaderboard/', Leaderboard.as_view(), name='leaderboard'),
    path('login/', loginView, name='login'),
    path('signup/', signupView, name='signup'),
    path('verify-email/', verify_email, name="verify_email"),

    # ===============================
    # Authenticated Users Only
    # ===============================
    path('quiz', QuestionList.as_view(), name="question_list"),
    path('quiz_taken', quiz_taken, name="quiz_taken"),
    path('quiz_created', quiz_created, name="quiz_created"),
    path('play-quiz/<int:category_id>/', PlayQuizView.as_view(), name='play'),
    path('quiz/new/', create_question, name="quiz_new"),
    path('analytics/', quiz_analytics, name="quiz_analytics"),
    path('quiz-results/', quiz_results, name="quiz_results"),
    path('results/<int:category_id>/', results, name='results'),
    path('category/', category_list, name="category"),
    path('search/', SearchResultListView.as_view(), name="search_result"),
    path('submission_result/', submission_Result, name='submission_result'),
    path('profile/', Profile.as_view(), name="profile"),
    path('profile-edit/<int:pk>/', EditProfile.as_view(), name="edit_profile"),
    path('messages/', MessageList.as_view(), name="messages"),
    path('messages/new/', CreateMessage.as_view(), name="messages_new"),
    path('messages/<uuid:pk>/', MessageDetail.as_view(), name="message_detail"),
    path('messages/delete/<uuid:pk>/',
         DeleteMessage.as_view(), name="message_delete"),
    path('announcement/', AnnouncementList.as_view(), name="announcements"),
    path('announcement/<uuid:pk>/', AnnouncementDetail.as_view(),
         name="announcement_detail"),

]

quizApp_Config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from quiz import views as quiz_views
from django.conf.urls import handler404, handler500, handler403

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quiz.urls')),
    path('', include('quiz.urls', namespace='quiz')),
    path('', include('pages.urls')),
    path('', include('allauth.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = quiz_views.error404
handler500 = quiz_views.error_500

quiz/forms.py
from django import forms
from django.utils.translation import gettext as _
from django.contrib.auth import get_user_model
from .models import Question, Choice, Category, Message

User = get_user_model()


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['author', 'category']

        def __init__(self, *args, **kwargs):
            self.author = kwargs.pop('author', None)
            super().__init__(*args, **kwargs)
            self.fields['category'].widget.attrs.update(
                {'class': 'form-control'})

        def save(self, commit=True):
            instance = super().save(commit=False)
            instance.author = self.author
            if commit:
                instance.save()
            return instance


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['author', 'question', 'category', 'image']

        def __init__(self, *args, **kwargs):
            self.author = kwargs.pop('author', None)
            super().__init__(*args, **kwargs)
            self.fields['question'].widget.attrs.update(
                {'class': 'form-control'})
            self.fields['image'].widget.attrs.update(
                {'class': 'form-control-file'})

        def save(self, commit=True):
            instance = super().save(commit=False)
            instance.author = self.author
            if commit:
                instance.save()
            return instance


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['sender', 'recipient', 'message']


class ChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ['choice_text', 'is_correct']
        widgets = {
            'question': forms.Textarea(attrs={'rows': 3, 'cols': 80})
        }


class ChoiceInlineFormset(forms.BaseInlineFormSet):
    def clean(self):
        super(ChoiceInlineFormset, self).clean()

        correct_choices_count = 0
        for form in self.forms:
            if not form.is_valid():
                return

            if form.cleaned_data and form.cleaned_data.get('is_correct') is True:
                correct_choices_count += 1

        try:
            assert correct_choices_count == Question.ALLOWED_NUMBER_OF_CORRECT_CHOICES
        except AssertionError:
            raise forms.ValidationError(
                _('Exactly one correct choice is allowed.'))

quiz/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Question, QuizProfile, Category, Message, Announcement, Choice, QuizResult
from users.models import CustomUser
from django.db.models import Q, Count
from operator import attrgetter
from chartjs.views.lines import BaseLineChartView
from django.forms import inlineformset_factory
from django.utils.timezone import timezone
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import Http404, HttpResponse
from io import BytesIO
from reportlab.pdfgen import canvas
from .forms import QuestionForm, ChoiceInlineFormset, ChoiceForm, CategoryForm
from django.db import transaction
from django.core.exceptions import ObjectDoesNotExist
from itertools import groupby
from django.contrib.auth import authenticate, login, get_user_model
from django.urls import reverse, reverse_lazy
from django.contrib import messages
import time
from urllib.parse import urlencode
from django.conf import settings
from django.contrib.auth.hashers import make_password
import random
from django.db.models import Count, Sum
from random import shuffle
from django.views import View
from django.views.generic import UpdateView, CreateView, DeleteView, ListView, DetailView, TemplateView
from django.core.mail import send_mail

# +++ Class Based Views


class QuestionList(LoginRequiredMixin, ListView):
    login_url = 'login'

    def get(self, request):
        quiz_profile = QuizProfile.objects.filter(user=request.user).annotate(
            total_score_annotation=Sum('total_score')).first()
        question = Question.objects.all().order_by('category', 'difficulty_level')
        question_group = {}
        for category, category_quizzes in groupby(question, key=attrgetter('category')):
            question_group[category] = {}
            for level, level_quizzes in groupby(category_quizzes, key=attrgetter('difficulty_level')):
                question_group[category][level] = list(level_quizzes)
        context = {'question_group': question_group,
                   'quiz_profile': quiz_profile}
        return render(request, 'question/question.html', context)


@login_required
def category_list(request):
    categories = Category.objects.all()
    quiz_profile = (
        QuizProfile.objects
        .filter(user=request.user)
        .annotate(total_score_annotation=Sum('total_score'))
        .first()
    )
    context = {'categories': categories, 'quiz_profile': quiz_profile}
    return render(request, 'question/category_list.html', context)


class SearchResultListView(ListView):
    model = Category
    context_object_name = 'categories'
    template_name = 'question/search_result.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        return Category.objects.filter(
            Q(category__icontains=query) | Q(category__icontains=query)
        )


class Leaderboard(LoginRequiredMixin, TemplateView):
    login_url = 'login'

    def get(self, request):
        top_quiz_profiles = QuizProfile.objects.order_by('-total_score')[:500]
        top_count = top_quiz_profiles.count()
        context = {
            'top_quiz_profiles': top_quiz_profiles,
            'total_count': top_count,
        }
        return render(request, 'leaderboard.html', context=context)


class Profile(TemplateView):
    template_name = 'profile/profile.html'


class EditProfile(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    login_url = 'login'
    fields = ["first_name", "last_name", "username", "gender"]
    template_name = 'profile/edit-profile.html'
    success_url = reverse_lazy('profile')


class MessageList(LoginRequiredMixin, ListView):
    model = Message
    login_url = 'login'
    context_object_name = "messages_list"
    template_name = "message/message.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sending'] = context['messages_list'].filter(
            sender=self.request.user)
        context['recieving'] = context['messages_list'].filter(
            recipient=self.request.user)
        context['sent'] = context['messages_list'].filter(sent=True).count()
        context['recieved'] = context['messages_list'].filter(
            recipient=self.request.user).count()
        return context


class MessageDetail(LoginRequiredMixin, DetailView):
    model = Message
    context_object_name = "message"
    login_url = 'login'
    template_name = "message/message-detail.html"


class CreateMessage(LoginRequiredMixin, CreateView):
    model = Message
    login_url = 'login'
    template_name = 'message/create-message.html'
    success_url = reverse_lazy('messages')
    fields = ['recipient', 'message']

    def form_valid(self, form):
        form.instance.sender = self.request.user
        return super(CreateMessage, self).form_valid(form)


class DeleteMessage(LoginRequiredMixin, DeleteView):
    model = Message
    login_url = 'login'
    context_object_name = "message"
    template_name = 'message/delete-message.html'
    success_url = reverse_lazy('messages')


class AnnouncementList(LoginRequiredMixin, ListView):
    model = Announcement
    login_url = 'login'
    context_object_name = "announcements"
    template_name = "announcement/announcement.html"

    def get_queryset(self):
        # Get the user's signup date
        signup_date = self.request.user.date_joined

        # Filter announcements created after the user's signup date
        queryset = super().get_queryset().filter(created_at__gte=signup_date)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['announcement_list'] = context['announcements']
        context['announcements_total'] = context['announcements'].count()
        return context


class AnnouncementDetail(LoginRequiredMixin, DetailView):
    model = Announcement
    login_url = 'login'
    context_object_name = "announcement"
    template_name = "announcement/announcement-detail.html"


@login_required
def submission_Result(request, attempted_question_pk):
    attempted_question = get_object_or_404(
        AttemptedQuestion, pk=attempted_question_pk)
    context = {
        'attempted_question': attempted_question,
    }
    return render(request, 'submission_result.html', context)


# def play_quiz(request, category_id):
#     category = Category.objects.get(pk=category_id)
#     questions = list(category.question_set.all())
#     random.shuffle(questions)
#     num_questions = len(questions)
#     current_question_index = int(request.GET.get('question_index', 0))

#     # Get user's quiz profile for the category
#     quiz_profile, created = QuizProfile.objects.get_or_create(
#         user=request.user, category=category)

#     if request.method == 'POST':
#         answer = request.POST.get('answer')
#         if answer:
#             request.session['answers'][current_question_index] = answer
#         if 'next' in request.POST:
#             current_question_index += 1
#         elif 'prev' in request.POST:
#             current_question_index -= 1
#     if 'answers' not in request.session:
#         request.session['answers'] = {}

#     # Save the quiz result when all questions are answered
#     if current_question_index == num_questions:
#         score = 0
#         for i, question in enumerate(questions):
#             if str(i) in request.session['answers']:
#                 if question.is_correct(request.session['answers'][str(i)]):
#                     score += 1
#         total_score = (score / num_questions) * 100
#         quiz_profile.total_score = total_score
#         quiz_profile.save()

#     # Get user's quiz history
#     quiz_history = QuizProfile.objects.filter(user=request.user)

#     context = {
#         'questions': questions,
#         'num_questions': num_questions,
#         'category': category,
#         'current_question_index': current_question_index,
#         'current_question_number': current_question_index + 1,
#         'answers': request.session.get('answers', {}),
#         'quiz_profile': quiz_profile,
#         'quiz_history': quiz_history
#     }

#     return render(request, 'question/quiz.html', context)

class PlayQuizView(View):
    template_name = 'question/quiz.html'
    questions_limit = 15  # Number of questions to show

    def get(self, request, category_id):
        category = get_object_or_404(Category, id=category_id)
        questions = list(Question.objects.filter(category=category))
        shuffle(questions)
        questions = questions[:self.questions_limit]

        # Retrieve previously selected answers from session
        answers = request.session.get('answers', {})

        return render(request, self.template_name, {
            'category': category,
            'questions': questions,
            'total_points': 150,
            'answers': answers,
        })

    def post(self, request, category_id):
        category = get_object_or_404(Category, id=category_id)
        questions = list(Question.objects.filter(category=category))
        shuffle(questions)
        questions = questions[:self.questions_limit]
        total_points = 150

        user_profile = QuizProfile.objects.get(user=request.user)

        # Retrieve previously selected answers from session
        answers = request.session.get('answers', {})

        for question in questions:
            answer = request.POST.get(f"question_{question.id}")

            if answer:
                choices = list(question.choices.all())
                correct_choices = list(filter(lambda c: c.is_correct, choices))

                if len(correct_choices) != 1:
                    raise ValueError(

templates/question/_category_form.html
<fieldset>
    <legend>Category Information</legend>
    {{ category_form.as_p }}
</fieldset>

templates/question/category_list.html
{% extends '_base.html' %}
{% load static %}
{% block title %}Category{% endblock title %}

{% block style %}
<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">

<style>
    section {
        width: 100%;
        height: 100vh;
        overflow: hidden;
    }

    main {
        margin: 0;
        width: 100%;
        height: 100%;
        display: flex;
        justify-content: center;
        font-size: 18px;
        font-family: fira sans;
    }

    nav {
        background-color: #3B0A6B;
    }

    nav ul {
        display: flex;
        width: 100%;
        height: 100%;
        justify-content: space-between;
        list-style-type: none;
    }

    nav ul li a {
        color: white;
        font-family: sans-serif;
        font-size: 17px;
    }

    .banner {
        display: flex;
        width: 20%;
        align-items: center;
        justify-content: space-between;
    }

    .nav-menu-actions {
        width: 20%;
        display: flex;
        justify-content: space-evenly;
        align-items: center;
    }

    .backdrop {
        position: fixed;
        top: 0;
        width: 100%;
        background: rgba(0, 0, 0, 0.8);
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
    }

    .backdrop h5 {
        color: white;
        font-size: 4rem;
        font-family: Arial rounded mt;
        top: 0;
        right: 20rem;
        position: fixed;
        cursor: pointer;
    }

    .search-backdrop {
        width: 60%;
        backdrop-filter: blur(4px);
    }

    .form-group {
        z-index: 4;
        width: 100%;
        background: rgba(0, 0, 0, 0.1);
        display: flex;
        align-items: center;
        justify-content: center;
        margin: 10rem auto;
        padding: 30px;
    }

    .form-group input {
        width: 100%;
        height: 50px;
        background: none;
        border: none;
        outline: none;
        border-left: 1px solid #fff;
        font-size: 20px;
        color: white;
        font-family: sans-serif;
        padding-left: 10px;
    }

    ::placeholder {
        color: white;
    }

    .not-showing {
        display: none;
    }

    @media (max-width: 1024px) {
        nav {
            width: 100%;
        }

    }

    .all-categories {
        min-width: 100%;
    }

    .categories {
        display: grid;
        grid-template-columns: auto auto auto;
        padding: 20px;
        grid-gap: 10px;
    }

    .category-item {
        border-radius: 5px;
        box-shadow: 0 5px 10px rgba(0, 0, 0, 0.1);
        border-top: 5px solid #3B0A6B;
        border-bottom: 5px solid #3B0A6B;
        text-align: left;
        height: 150px;
        width: 90%;
        margin: 0;
        display: flex;
        padding: 2rem;
        flex-direction: column;
        justify-content: space-between;
    }

    h2 {
        color: #3B0A6B;
        font-size: 30px;
        font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;
    }

    span a {
        padding: 10px 30px;
        border-radius: 4px;
        border: 2px solid #3B0A6B;
        color: black;
        font-family: sans-serif;
        text-decoration: none;
        font-weight: 800;
    }

    .actions {
        display: flex;
        justify-content: space-between;
    }

    .addQuizButton {
        position: absolute;
        color: navy;
    }

    .quiz-info {
        display: flex;
        align-items: center;
        justify-content: space-between;
    }
</style>
{% endblock style %}

{% block content %}
<nav>
    <ul>
        <div class="banner">
            <li><a href="{% url 'home_page' %}" style="font-family: cooper black; font-size: 40px;">Quizzer</a></li>
        </div>
        <div class="nav-menu-actions">
            <li><a href="#"><i class="fa fa-search"></i></a></li>
            <li><i class="fa fa-copyright"></i> <b>{{ quiz_profile.total_score_annotation }}</b></li>
            <li><a href="{% url 'quiz:profile' %}" class="profile_name">{{ request.user.first_name|slice:":1" }}</a></li>
        </div>
    </ul>
</nav>

<section class="all-categories">
    <div class="categories">
        {% for category_data in categories %}
        <div class="category-item">
            <div class="quiz-info">
                <h1>{{ category_data.category }}</h1>
                <h1>Points: 150</h1>
            </div>
            <div class="actions">
                <span><a href="{% url 'quiz:play' category_data.id %}?question_index=0">Play</a></span>
                <span><a href="{% url 'quiz:play' category_data.id %}?question_index=0">Leaderboard</a></span>
            </div>
        </div>
        {% endfor %}

    </div>

</section>



<section class="backdrop not-showing">
    <h5 class="modal-search-box-btn">X</h5>
    <div class="search-backdrop">
        <form action="{% url 'quiz:search_result' %}" method="get">
            <div class="form-group">
                <input type="text" placeholder="Search" name="q" aria-label="Search">
            </div>
        </form>
    </div>
</section>
{% endblock content %}

{% block javascript %}
<script>
    const show_modal_box_btn = document.querySelector(".fa-search")
    const modal_box = document.querySelector(".backdrop");
    const close_modal_box_btn = document.querySelector(".modal-search-box-btn");
    let showModalBox = false;

    show_modal_box_btn.addEventListener("click", (e) => {
        showModalBox = !showModalBox;
        console.log(showModalBox)

        if (showModalBox == true) {
            modal_box.classList.remove('not-showing')
        }
    })
    close_modal_box_btn.addEventListener('click', (e) => {
        showModalBox = !showModalBox
        modal_box.classList.add('not-showing');
    })
</script>
{% endblock javascript %}

templates/question/quiz.html
<!-- quiz.html -->
{% extends '_base.html' %}


{% block style %}
<style>
  :root {
    --color-primary: #3B0A6B;
    --color-secondary: lightblue;
  }


  /* quiz.css */

  .quiz-container {
    max-width: 600px;
    margin: 10% auto;
    box-shadow: 0 5px 10px rgba(0, 0, 0, .2);
    padding: 2rem;
    border-radius: 10px;
  }

  #quiz-form {
    margin-top: 3rem;
  }

  .question {
    display: none;
  }

  .question h3 {
    position: relative;
    background-color: #f443366a;
    display: inline-block;
    margin-left: auto;
    padding: 10px 2rem;
    border-radius: 5px;
    text-align: left;
    margin: 0;
    text-align: right;
  }

  .question p {
    text-align: center;
    font-size: 18px;
    font-weight: bold;
    font-family: sans-serif;
  }

  .question.active {
    display: block;
  }

  ul {
    list-style-type: none;
    padding: 0;
    display: grid;
    grid-template-columns: auto auto;
    width: 100%;
    grid-gap: 10px;
  }

  li {
    margin-bottom: 10px;
    padding: 10px;
    border-radius: 5px;
    background-color: var(--color-secondary);
    font-size: 17px;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
  }

  .navigation-buttons {
    margin-top: 20px;
    text-align: center;
  }

  .navigation-buttons button {
    padding: 10px 20px;
    margin: 0 5px;
    background-color: #4CAF50;
    color: #fff;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }

  .navigation-buttons button:disabled {
    background-color: #ddd;
    cursor: not-allowed;
  }

  .navigation-buttons #submit-btn {
    background-color: #f44336;
    margin: 3rem auto;
  }

  h1 {
    text-align: center;
    font-family: georgia pro;
  }
</style>

{% endblock style %}



{% block content %}

<div class="quiz-container">
  <h1>{{ category.category }} Quiz</h1>
  <form id="quiz-form" method="post" action="{% url 'quiz:play' category.id %}">
    {% csrf_token %}
    {% for question in questions %}
    <div class="question {% if forloop.first %}active{% endif %}" id="question_{{ question.id }}">
      <h3>Q: {{ forloop.counter }}</h3>
      <p>{{ question.question }}</p>
      <ul>
        {% for choice in question.choices.all %}
        <li>
          <input type="radio" name="question_{{ question.id }}" value="{{ choice.id }}">
          <label for="choice_{{ question.id }}_{{ choice.id }}">{{ choice.choice_text }}</label>
        </li>
        {% endfor %}
      </ul>
    </div>
    {% endfor %}

    <div class="navigation-buttons">
      <button type="button" id="prev-btn" onclick="navigateQuestion(-1)" disabled>Previous</button>
      <button type="button" id="next-btn" onclick="navigateQuestion(1)">Next</button>
      <button type="submit" id="submit-btn" style="display: none;">Submit</button>
    </div>
  </form>
</div>

<script>
  var currentQuestion = 0;
  var questions = document.querySelectorAll('.question');
  var prevButton = document.getElementById('prev-btn');
  var nextButton = document.getElementById('next-btn');
  var submitButton = document.getElementById('submit-btn');

  showQuestion(currentQuestion);

  function showQuestion(index) {
    questions.forEach(function (question, idx) {
      if (idx === index) {
        question.classList.add('active');
      } else {
        question.classList.remove('active');
      }
    });

    prevButton.disabled = index === 0;
    nextButton.disabled = index === questions.length - 1;
    submitButton.style.display = index === questions.length - 1 ? 'block' : 'none';
  }

  function navigateQuestion(direction) {
    currentQuestion += direction;
    showQuestion(currentQuestion);
  }
</script>
{% endblock %}

templates/question/quiz_results.html
{% extends '_base.html' %}
{% load static %}
{% block title %}Quiz Results{% endblock title %}

{% block style %}
{% endblock style %}

{% block content %}
<h1>Quiz Results</h1>
<hr>

{% if quiz_results %}
{% for quiz_result in quiz_results %}
<h2>{{ quiz_result.category.category }}</h2>
{% if quiz_result.results %}
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Username</th>
            <th>Score</th>
        </tr>
    </thead>
    <tbody>
        {% for user, score in quiz_result.results.items %}
        <tr>
            <td>{{ user }}</td>
            <td>{{ score }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<p>No quiz results found.</p>
{% endif %}
{% endfor %}
{% else %}
<p>No quiz results found.</p>
{% endif %}

<br>

<a href="{% url 'quiz:category' %}" class="btn btn-primary">Back to Categories</a>

<br><br>

<form action="{% url 'quiz:quiz_results' %}" method="get">
    <button type="submit" name="pdf" value="1" class="btn btn-primary">Download PDF</button>
</form>
{% endblock %}

templates/question/search_result.html
{% extends '_base.html' %}
{% load static %}
{% block title %}Category{% endblock title %}

{% block style %}
<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">

<style>
    section {
        width: 100%;
        height: 100vh;
        overflow: hidden;
    }

    main {
        margin: 0;
        width: 100%;
        height: 100%;
        display: flex;
        justify-content: center;
        font-size: 18px;
        font-family: fira sans;
    }

    nav {
        background-color: #3B0A6B;
    }

    nav ul {
        display: flex;
        width: 100%;
        height: 100%;
        justify-content: space-between;
        list-style-type: none;
    }

    nav ul li a {
        color: white;
        font-family: sans-serif;
        font-size: 17px;
    }

    .banner {
        display: flex;
        width: 20%;
        align-items: center;
        justify-content: space-between;
    }

    .nav-menu-actions {
        width: 20%;
        display: flex;
        justify-content: space-evenly;
        align-items: center;
    }

    .backdrop {
        position: fixed;
        top: 0;
        width: 100%;
        background: rgba(0, 0, 0, 0.8);
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
    }

    .backdrop h5 {
        color: white;
        font-size: 4rem;
        font-family: Arial rounded mt;
        top: 0;
        right: 20rem;
        position: fixed;
        cursor: pointer;
    }

    .search-backdrop {
        width: 60%;
        backdrop-filter: blur(4px);
    }

    .form-group {
        z-index: 4;
        width: 100%;
        background: rgba(0, 0, 0, 0.1);
        display: flex;
        align-items: center;
        justify-content: center;
        margin: 10rem auto;
        padding: 30px;
    }

    .form-group input {
        width: 100%;
        height: 50px;
        background: none;
        border: none;
        outline: none;
        border-left: 1px solid #fff;
        font-size: 20px;
        color: white;
        font-family: sans-serif;
        padding-left: 10px;
    }

    ::placeholder {
        color: white;
    }

    .not-showing {
        display: none;
    }

    @media (max-width: 1024px) {
        nav {
            width: 100%;
        }

    }

    .all-categories {
        min-width: 100%;
    }

    .categories {
        display: grid;
        grid-template-columns: auto auto auto auto;
        grid-column-gap: 20px;
        padding: 20px;
    }

    .category-item {
        border-radius: 5px;
        box-shadow: 0 5px 10px rgba(0, 0, 0, 0.1);
        border-top: 5px solid #3B0A6B;
        border-bottom: 5px solid #3B0A6B;
        text-align: left;
        height: 150px;
        display: flex;
        padding: 2rem;
        flex-direction: column;
        justify-content: space-between;
    }

    h2 {
        color: #3B0A6B;
        font-size: 30px;
        font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;
    }

    span a {
        padding: 10px 30px;
        border-radius: 4px;
        border: 2px solid #3B0A6B;
        color: black;
        font-family: sans-serif;
        text-decoration: none;
        font-weight: 800;
    }

    .actions {
        display: flex;
        justify-content: space-between;
    }

    .quiz-info {
        display: flex;
        align-items: center;
        justify-content: space-between;
    }
</style>
{% endblock style %}

{% block content %}
<nav>
    <ul>
        <div class="banner">
            <li><a href="{% url 'home_page' %}" style="font-family: cooper black; font-size: 40px;">Quizzer</a></li>
        </div>
        <div class="nav-menu-actions">
            <li><a href="#"><i class="fa fa-search"></i></a></li>
            <li><i class="fa fa-copyright"></i>0.00</li>
            <li><a href="{% url 'quiz:profile' %}" class="profile_name">{{ request.user.first_name|slice:":1" }}</a></li>
        </div>
    </ul>
</nav>

<section class="all-categories">
    <div class="categories">
        {% for category_data in categories %}
        <div class="category-item">
            <div class="quiz-info">
                <h1>{{ category_data.category }}</h1>
                <h1>Points: 150</h1>
            </div>
            <div class="actions">
                <span><a href="{% url 'quiz:play' category_data.id %}?question_index=0">Play</a></span>
                <span><a href="{% url 'quiz:play' category_data.id %}?question_index=0">Leaderboard</a></span>
            </div>
        </div>
        {% endfor %}
    </div>
</section>

<section class="backdrop not-showing">
    <h5 class="modal-search-box-btn">X</h5>
    <div class="search-backdrop">
        <form action="{% url 'quiz:search_result' %}" method="get">
            <div class="form-group">
                <input type="text" placeholder="Search" name="q" aria-label="Search">
            </div>
        </form>
    </div>
</section>
{% endblock content %}

{% block javascript %}
<script>
    const show_modal_box_btn = document.querySelector(".fa-search")
    const modal_box = document.querySelector(".backdrop");
    const close_modal_box_btn = document.querySelector(".modal-search-box-btn");
    let showModalBox = false;

    show_modal_box_btn.addEventListener("click", (e) => {
        showModalBox = !showModalBox;
        console.log(showModalBox)

        if (showModalBox == true) {
            modal_box.classList.remove('not-showing')
        }
    })
    close_modal_box_btn.addEventListener('click', (e) => {
        showModalBox = !showModalBox
        modal_box.classList.add('not-showing');
    })
</script>
{% endblock javascript %}