quiz/urls.py
from django.urls import path
from .views import (
    QuestionList,
    loginView,
    # play_quiz,
    PlayQuizView,
    Leaderboard,
    submission_Result,
    Profile,
    signupView,
    verify_email,
    category_list,
    MessageDetail,
    MessageList,
    AnnouncementDetail,
    AnnouncementList,
    CreateMessage,
    EditProfile,
    create_question,
    DeleteMessage,
    SearchResultListView,
    quiz_results,
    results,
    quiz_analytics,
    quiz_taken,
    quiz_created
)
app_name = "quiz"


urlpatterns = [
    # ===============================
    # Both Unauthenticated Users
    # ===============================
    path('leaderboard/', Leaderboard.as_view(), name='leaderboard'),
    path('login/', loginView, name='login'),
    path('signup/', signupView, name='signup'),
    path('verify-email/', verify_email, name="verify_email"),

    # ===============================
    # Authenticated Users Only
    # ===============================
    path('quiz', QuestionList.as_view(), name="question_list"),
    path('quiz_taken', quiz_taken, name="quiz_taken"),
    path('quiz_created', quiz_created, name="quiz_created"),
    path('play-quiz/<int:category_id>/', PlayQuizView.as_view(), name='play'),
    path('quiz/new/', create_question, name="quiz_new"),
    path('analytics/', quiz_analytics, name="quiz_analytics"),
    path('quiz-results/', quiz_results, name="quiz_results"),
    path('results/<int:category_id>/', results, name='results'),
    path('category/', category_list, name="category"),
    path('search/', SearchResultListView.as_view(), name="search_result"),
    path('submission_result/', submission_Result, name='submission_result'),
    path('profile/', Profile.as_view(), name="profile"),
    path('profile-edit/<int:pk>/', EditProfile.as_view(), name="edit_profile"),
    path('messages/', MessageList.as_view(), name="messages"),
    path('messages/new/', CreateMessage.as_view(), name="messages_new"),
    path('messages/<uuid:pk>/', MessageDetail.as_view(), name="message_detail"),
    path('messages/delete/<uuid:pk>/',
         DeleteMessage.as_view(), name="message_delete"),
    path('announcement/', AnnouncementList.as_view(), name="announcements"),
    path('announcement/<uuid:pk>/', AnnouncementDetail.as_view(),
         name="announcement_detail"),

]

quizApp_Config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from quiz import views as quiz_views
from django.conf.urls import handler404, handler500, handler403

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quiz.urls')),
    path('', include('quiz.urls', namespace='quiz')),
    path('', include('pages.urls')),
    path('', include('allauth.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = quiz_views.error404
handler500 = quiz_views.error_500

templates/message/create-message.html
{% extends '_base.html' %}
{% load static %}
{% block title %}New Message{% endblock title %}
{% block style %}

<style>
    main {
        margin: 0;
        width: auto;
        height: auto;
        padding: 0;
    }

    h1 {
        font-family: sans-serif;
        font-size: 2rem;
        text-align: center;
    }

    .top-menu {
        padding: 20px;
        display: flex;
        align-items: center;
        justify-content: space-between;
    }

    .top-menu a {
        padding: 10px;
        background-color: black;
        border-radius: 5px;
        color: white;
        text-decoration: none;
        font-family: fira sans;
        font-weight: 800;
    }

    form {
        width: auto;
        padding: 20px;
    }

    label {
        font-family: sans-serif;
        font-weight: 700;
        font-size: 14px;
    }

    select {
        width: 100%;
        height: 30px;
    }

    textarea {
        width: 100%;
    }

    input {
        width: 100%;
        height: 40px;
        background-color: green;
        color: white;
        font-weight: 900;
        border: none;
    }
</style>
{% endblock style %}

{% block content %}

<section>
    <main>
        <div class="top-menu">
            <h1>Send a message</h1>
            <a href="{% url 'quiz:messages' %}"><i class="fa fa-chevron-left"></i> Go Back</a>
        </div>

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="SEND">
        </form>
    </main>
</section>
{% endblock content %}

templates/message/delete-message.html
{% extends '_base.html' %}
{% load static %}
{% block title %}Delete Message{% endblock title %}
{% block style %}

<style>
    main {
        margin: 0;
        width: auto;
        height: auto;
        padding: 0;
    }

    h1 {
        font-family: sans-serif;
        font-size: 2rem;
        text-align: center;
    }
    
    .top-menu {
        padding: 20px;
        display: flex;
        align-items: center;
        justify-content: space-between;
    }

    .top-menu a {
        padding: 10px;
        background-color: black;
        border-radius: 5px;
        color: white;
        text-decoration: none;
        font-family: fira sans;
        font-weight: 800;
    }

    form {
        width: auto;
        padding: 20px;
    }

    input {
        width: 100%;
        height: 40px;
        background-color: red;
        color: white;
        font-weight: 900;
        border: none;
    }
</style>
{% endblock style %}

{% block content %}

<section>
    <main>
        <div class="top-menu">
            <h1>Delete message</h1>
            <a href="{% url 'messages' %}"><i class="fa fa-chevron-left"></i> Go Back</a>
        </div>

        <form method="post">
            {% csrf_token %}
            <p>Are you sure</p>
            {{ form.as_p }}
            <input type="submit" value="DELETE">
        </form>
    </main>
</section>
{% endblock content %}

templates/message/message-detail.html
{% extends '_base.html' %}
{% load static %}
{% block title %}Message{% endblock title %}
{% block style %}
<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">

<style>
    h1 {
        font-family: sans-serif;
        font-size: 2rem;
        text-align: center;
    }

    .top-menu {
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding: 20px;
    }

    .top-menu a {
        padding: 10px;
        background-color: black;
        border-radius: 5px;
        color: white;
        text-decoration: none;
        font-family: fira sans;
        font-weight: 800;
    }
</style>
{% endblock style %}

{% block content %}
{% include '_navbar.html' %}
<section>
    <main>
        <div class="top-menu">
            <h1>Message Detail</h1>
            <a href="{% url 'quiz:messages' %}"><i class="fa fa-chevron-left"> </i>Go back</a>
        </div>

        <div class="messages">
            <h3>From: {{ message.sender }}</h3>
            <h3>To: {{ message.recipient }}</h3>
            <p><b>Content: </b> {{ message.message }}</p>
            <p>Date: {{ message.created_at }}</p>
        </div>
    </main>
</section>
{% endblock content %}

templates/message/message.html
{% extends '_base.html' %}
{% load static %}
{% block title %}Messages{% endblock title %}
{% block style %}
<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">

<style>
    h1 {
        font-family: sans-serif;
        font-size: 2rem;
        text-align: center;
    }

    .top-menu {
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding: 20px;
    }

    .top-menu a {
        padding: 10px;
        background-color: black;
        border-radius: 5px;
        color: white;
        text-decoration: none;
        font-family: fira sans;
        font-weight: 800;
    }

    .messages {
        width: 99%;
        height: 93%;
        padding-top: 20px;
        border-radius: 4px;
    }

    .announcement-item {
        color: black;
        background: whitesmoke;
        margin-bottom: 20px;
        padding: 20px;
        border-bottom: 1px solid #000;
    }

    .announcement-item a {
        color: black;
        text-decoration: none;
    }

    section {
        width: 100%;
    }

    main {
        height: 100%;
    }

    .messages {
        height: auto;
        padding: 30px;
        width: auto;
    }

    table {
        width: 100%;
        text-align: left;
    }

    th {
        padding: 20px;
        font-family: sans-serif;
        background-color: #3B0A6B;
        color: white;
    }

    td {
        background-color: whitesmoke;
        padding: 20px;
        font-family: sans-serif;
    }

    td a {
        text-decoration: none;
        padding: 10px 10px;
        /* display: flex; */
    }

    td a.edit {
        background-color: blue;
        border-radius: 5px;
        color: white;
        margin-bottom: 5px;
    }

    td a.delete {
        background-color: red;
        border-radius: 5px;
        color: white;
    }
</style>
{% endblock style %}

{% block content %}
{% include '_navbar.html' %}
<section>
    <main>
        <div class="top-menu">
            <h1>Messages</h1>
            <a href="{% url 'quiz:messages_new' %}"><i class="fa fa-plus"></i> Compose</a>
        </div>

        <div class="messages">
            <table>
                <tr>
                    <th>Send / Recieve</th>
                    <th>User</th>
                    <th>Date</th>
                    <th colspan="1">Action</th>
                </tr>
                {% for send in sending reversed %}
                <tr>
                    <td>Send</td>
                    <td>{{ send.recipient }}</td>
                    <td>{{ send.created_at }}</td>
                    <td><a href="{% url 'quiz:message_detail' send.id %}" class="edit">View</a> <a href="{% url 'quiz:message_delete' send.id %}" class="delete">Delete</a></td>
                </tr>
                {% endfor %}

                {% for recieve in recieving reversed %}
                <tr>
                    <td>Recieve</td>
                    <td>{{ recieve.sender }}</td>
                    <td>{{ recieve.created_at }}</td>
                    <td><a href="{% url 'quiz:message_detail' recieve.id %}" class="edit">View</a> <a href="{% url 'quiz:message_delete' recieve.id %}" class="delete">Delete</a></td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </main>
</section>
{% endblock content %}