quiz/urls.py
from django.urls import path
from .views import (
    QuestionList,
    loginView,
    # play_quiz,
    PlayQuizView,
    Leaderboard,
    submission_Result,
    Profile,
    signupView,
    verify_email,
    category_list,
    MessageDetail,
    MessageList,
    AnnouncementDetail,
    AnnouncementList,
    CreateMessage,
    EditProfile,
    create_question,
    DeleteMessage,
    SearchResultListView,
    quiz_results,
    results,
    quiz_analytics,
    quiz_taken,
    quiz_created
)
app_name = "quiz"


urlpatterns = [
    # ===============================
    # Both Unauthenticated Users
    # ===============================
    path('leaderboard/', Leaderboard.as_view(), name='leaderboard'),
    path('login/', loginView, name='login'),
    path('signup/', signupView, name='signup'),
    path('verify-email/', verify_email, name="verify_email"),

    # ===============================
    # Authenticated Users Only
    # ===============================
    path('quiz', QuestionList.as_view(), name="question_list"),
    path('quiz_taken', quiz_taken, name="quiz_taken"),
    path('quiz_created', quiz_created, name="quiz_created"),
    path('play-quiz/<int:category_id>/', PlayQuizView.as_view(), name='play'),
    path('quiz/new/', create_question, name="quiz_new"),
    path('analytics/', quiz_analytics, name="quiz_analytics"),
    path('quiz-results/', quiz_results, name="quiz_results"),
    path('results/<int:category_id>/', results, name='results'),
    path('category/', category_list, name="category"),
    path('search/', SearchResultListView.as_view(), name="search_result"),
    path('submission_result/', submission_Result, name='submission_result'),
    path('profile/', Profile.as_view(), name="profile"),
    path('profile-edit/<int:pk>/', EditProfile.as_view(), name="edit_profile"),
    path('messages/', MessageList.as_view(), name="messages"),
    path('messages/new/', CreateMessage.as_view(), name="messages_new"),
    path('messages/<uuid:pk>/', MessageDetail.as_view(), name="message_detail"),
    path('messages/delete/<uuid:pk>/',
         DeleteMessage.as_view(), name="message_delete"),
    path('announcement/', AnnouncementList.as_view(), name="announcements"),
    path('announcement/<uuid:pk>/', AnnouncementDetail.as_view(),
         name="announcement_detail"),

]

quizApp_Config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from quiz import views as quiz_views
from django.conf.urls import handler404, handler500, handler403

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quiz.urls')),
    path('', include('quiz.urls', namespace='quiz')),
    path('', include('pages.urls')),
    path('', include('allauth.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = quiz_views.error404
handler500 = quiz_views.error_500

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quizer | {% block title %}{% endblock title %}</title>

    <!-- Vendor  Css -->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/aos/aos.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/boxicons/css/boxicons.min' %}">
    <link rel="stylesheet" href="{% static 'vendor/swiper/swiper-bundle.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/jquery-ui/jquery-ui.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/chart.js/Chart.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/fontawesome-free/css/all.min.css' %}">
    <!-- <link rel="stylesheet" href="{% static 'vendor/fontawesome-free/css/svg-with-js.min.css' %}"> -->

    {% block style %}
    {% endblock style %}
</head>

<body>

    {% block content %}
    {% endblock content %}

    <!-- Vendor Js -->
    <script src="{% static 'vendor/aos/aos.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
    <script src="{% static 'vendor/jquery-3.5.1.min.css' %}"></script>
    <script src="{% static 'vendor/chart.js/Chart.bundle.min.js' %}"></script>
    <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
    <!-- Js -->
    <script src="{% static 'assets/js/main.js' %}"></script>

    {% block javascript %}
    {% endblock javascript %}
</body>

</html>

templates/_navbar.html
<style>
    .side-nav a {
        display: flex;
        color: #710988;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        text-decoration: none;
    }

    .side-nav {
        position: fixed;
        width: 140px;
        /* border-right: 10px solid black; */
        box-shadow: 3px 0 10px rgba(0, 0, 0, 0.3);
        height: 100%;
        background-color: #fff;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
    }

    .side-nav a i {
        color: #3B0A6B;
        font-size: 20px;
        width: 100%;
        height: 70px;
        gap: 10px;
        transition: all .4s ease-in-out;
        display: flex;
        align-items: center;
        justify-content: center;
        font-family: sans-serif;
        font-style: normal;
        font-weight: 800;
    }

    .side-nav ul {
        width: 100%;
    }

    .side-nav ul li {
        width: 100%;
    }

    .side-nav a i span {
        font-size: 14px;
    }

    .side-nav a i.active {
        color: #fff;
        background-color: #3B0A6B;
    }

    .side-nav a i:hover {
        color: #fff;
        background-color: #3B0A6B;
    }

    .side-nav p {
        margin-bottom: 27px;
        font-size: 21px;
        font-family: bree serif;
    }

    .side-nav li {
        margin-bottom: 20px;
    }

    @media (max-width: 890px) {
        .side-nav {
            display: none;
        }
    }
</style>

<div class="navbar-container">
    <div class="side-nav">
        <ul style="list-style-type: none; padding: 0;">
            {% if user.is_authenticated %}
            {% url 'home_page' as home_page %}
            <li>
                <a href="{{ home_page }}" title="Home">
                    <i class="{% if home_page == request.path %} active {% endif %}"> <span>Dashboard</span></i>
                </a>
            </li>

            {% url 'quiz:category' as category %}
            <li>
                <a href="{{category}}" title="Quiz">
                    <i class="{% if category == request.path %} active {% endif %}" aria-hidden="true"> <span>Quiz</span></i>
                </a>
            </li>

            {% url 'quiz:messages' as messages %}
            <li>
                <a href="{{ messages }}" title="Messages">
                    <i class="{% if messages == request.path %} active {% endif %}" aria-hidden="true"> <span>Messages</span></i>
                </a>
            </li>

            {% url 'quiz:announcements' as announcements %}
            <li>
                <a href="{{ announcements }}" title="Announcements">
                    <i class="{% if announcements == request.path %} active {% endif %}" aria-hidden="true"> <span>Announcement</span></i>
                </a>
            </li>

            {% url 'quiz:profile' as profile %}
            <li>
                <a href="{{ profile }}" title="Profile">
                    <i class="{% if profile == request.path %} active {% endif %}" aria-hidden="true"> <span>profile</span></i>
                </a>
            </li>

            {% url 'account_logout' as account_logout %}
            <li>
                <a href="{{ account_logout }}" title="Profile">
                    <i aria-hidden="true"> <span>Logout</span></i>
                </a>
            </li>

            {% else %}
            {% url 'home_page' as home_page %}
            <li>
                <a href="{{ home_page }}" title="Home">
                    <i class="{% if home_page == request.path %} active {% endif %}"> <span>Home</span></i>
                </a>
            </li>

            {% url 'about_page' as about_page %}
            <li>
                <a href="{{about_page}}" title="About">
                    <i class="{% if about_page == request.path %} active {% endif %}" aria-hidden="true"> <span>About</span></i>
                </a>
            </li>

            <li>
                <a href="" title="FAQs">
                    <i class="" aria-hidden="true"> <span>FAQs</span></i>
                </a>
            </li>

            {% url 'contact_page' as contact_page %}
            <li>
                <a href="{{ contact_page }}" title="Contact">
                    <i class="{% if contact_page == request.path %} active {% endif %}" aria-hidden="true"> <span>Contact</span></i>
                </a>
            </li>
            {% endif %}
        </ul>
    </div>
</div>

templates/about.html
{% extends '_base.html' %}
{% load static %}
{% block title %}About{% endblock title %}

{% block style %}
<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">

<style>
    section {
        background-color: black;
        padding: 0;
    }

    main {
        margin-right: 0;
        height: 100vh;
        margin-right: 0;
    }

    .video-wrapper {
        position: relative;
        width: 100%;
        height: 100%;
        overflow: hidden;
        text-align: center;
        display: flex;
        align-items: center;
        justify-content: center;
        color: white;
    }

    video {
        object-fit: cover;
        height: 100%;
        width: 100%;
        position: absolute;
        top: 0;
        left: 0;
    }

    .box-content-about {
        z-index: 2;
    }

    .box-content-about h2 {
        font-size: 3rem;
        font-family: gill sans MT;
    }

    .box-content-about h2 span {
        color: orange;
    }

    .box-content-about h5 {
        font-size: 1rem;
        font-family: Microsoft sans serif;
    }

    .box-content-about p {
        font-size: 24px;
        font-family: corbel;
    }

    .box-content-about a {
        padding: 10px 30px;
        border-radius: 40px;
        border: 2px solid #fff;
        text-decoration: none;
        color: orange;
        font-family: corbel;
    }
</style>
{% endblock style %}

{% block content %}
{% include '_navbar.html' %}

<section>
    <main>
        <div class="video-wrapper">
            <video playsinline autoplay muted loop poster="cake.jpg">
                <source src="{% static 'assets/img/pexels-louai-munajim-5818973.mp4' %}" type="video/mp4">
                Your browser does not support the video tag
            </video>
            <div class="box-content-about">
                <h2>About <span>Quizzer</span></h2>
                <h5>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur ab qui placeat ipsa omnis molestias nisi odit nulla eveniet perferendis.</h5>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi explicabo fugit nesciunt voluptatem iste, voluptate ipsum, recusandae aliquam ea et debitis nisi quaerat soluta veritatis voluptatibus consequuntur hic. Corporis vero pariatur nostrum rerum quia rem tenetur quidem molestias molestiae? Accusantium tempore animi error alias! Atque deserunt architecto ipsam error nulla.</p>
                <a href="">Contact Us</a>
            </div>
        </div>
    </main>
</section>
{% endblock content %}

templates/contact.html
{% extends '_base.html' %}
{% load static %}
{% block title %}Contact{% endblock title %}
{% block style %}
<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
<style>
    h1 {
        font-family: sans-serif;
        font-size: 2rem;
        text-align: center;
    }

    .top-menu {
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding: 20px;
    }

    .top-menu a {
        padding: 10px;
        background-color: black;
        border-radius: 5px;
        color: white;
        text-decoration: none;
    }

    .geolocation iframe {
        width: 100%;
        height: 300px;
        background-color: red;
    }

    .form-content {
        display: flex;
        justify-content: space-between;
    }

    .contact-info {
        width: 50%;
    }

    .contact-info h3 {
        font-size: 3rem;
        font-family: cooper black;
    }

    .contact-info ul {
        list-style-type: none;
        padding: 0;
    }

    .contact-info ul li {
        font-size: 17px;
        font-family: fira sans;
        margin-bottom: 20px;
        font-weight: 700;
    }

    .contact-info ul li i {
        padding: 10px;
        border-radius: 50px;
        border: 1px solid black;
        margin-right: 10px;
    }

    .container {
        width: 50%;
        height: auto;
        padding: 20px;
    }

    .container form {
        width: 100%;
    }

    .container .form-group {
        width: 100%;
        margin-bottom: 10px;
    }

    .container .form-group input {
        width: 100%;
        height: 40px;
        font-weight: 700;
        outline: none;
        border: 1px solid black;
        font-family: fira sans;
    }

    textarea {
        width: 100%;
        font-weight: 700;
        outline: none;
        height: 100px;
        font-family: fira sans;
        border: 1px solid black;
    }

    input[type=submit] {
        width: 30%;
        height: 50px;
        background-color: black;
        color: white;
        border-radius: 5px;
        font-size: 20px;
        border: none;
        outline: none;
    }

    .message-error,
    .message-success {
        width: 100%;
        height: 70px;
        color: white;
        text-transform: capitalize;
        font-family: fira sans;
        font-weight: 800;
        display: flex;
        align-items: center;
        justify-content: center;
        margin-bottom: 10px;
    }

    .message-error {
        background-color: red;
    }

    .message-success {
        background-color: green;
    }
</style>
{% endblock style %}

{% block content %}
{% include '_navbar.html' %}
<section>
    <main>
        <div class="top-menu">
            <h1>Contact Us</h1>
            <a href="{% url 'home_page' %}" class="btn goBack"><i class="fa fa-chevron-left"></i> Go Back</a>
        </div>



        <div class="form-content">
            <div class="contact-info">
                <h3>Quizzer</h3>
                <ul>
                    <li><i class="fa fa-envelope"></i> quizzer@support.com</li>
                    <li><i class="fa fa-map"></i> Enugu</li>
                    <li><i class="fa fa-phone"></i> +1 234-5678</li>
                </ul>
            </div>
            <div class="contact-container container">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" name="firstName" id="firstName" placeholder="First name">
                    </div>
                    <div class="form-group">
                        <input type="text" name="lastName" id="lastName" placeholder="Last name">
                    </div>
                    <div class="form-group">
                        <input type="email" name="email" id="email" placeholder="Email Address">
                    </div>
                    <div class="form-group">
                        <input type="text" name="phoneNumber" id="phoneNumber" placeholder="Phone Number">
                    </div>
                    <div class="form-group">
                        <textarea name="message" id="message" cols="30" rows="10" placeholder="Message"></textarea>
                    </div>
                    {% for message in messages %}
                    {% if message.tags == 'error' %}
                    <div class="message-error">
                        <h3>{{ message }}</h3>
                    </div>
                    {% endif %}
                    {% if message.tags == 'success' %}
                    <div class="message-success">
                        <h3>{{ message }}</h3>
                    </div>
                    {% endif %}
                    {% endfor %}
                    <input type="submit" value="SEND">
                </form>
            </div>
        </div>
    </main>
</section>
{% endblock content %}

templates/error_404.html
{% extends '_base.html' %}
{% load static %}
{% block title %}{{ page_title }}{% endblock title %}

{% block content %}
<h1>Page not found</h1>
{% endblock content %}

templates/error_500.html
{% extends '_base.html' %}
{% load static %}
{% block title %}{{ page_title }}{% endblock title %}

{% block content %}
<h1>Page not found</h1>
{% endblock content %}

templates/index.html
{% extends '_base.html' %}
{% load static %}
{% block title %}Home{% endblock title %}

{% block style %}
<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
<style>
    .leaderboard {
        text-decoration: none;
        color: white;
        font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
    }

    canvas {
        background-color: red;
        width: 100%;
        height: 100%;
    }

    .nerd,
    .rookie {
        display: flex;
        align-items: center;
        justify-content: center;
        height: 100%;
        flex-direction: column;
    }

    .nerd img,
    .rookie img {
        width: 50%;
    }

    .leaderboard-table {
        width: 100%;
        border-collapse: collapse;
    }

    .leaderboard-table th,
    .leaderboard-table td {
        padding: 1rem;
        text-align: center;
    }

    .leaderboard-table th {
        background-color: #f2f2f2;
        font-weight: bold;
        font-size: 14px;
        font-family: "Arial", sans-serif;
        border-bottom: 2px solid #ddd;
    }

    .leaderboard-table td {
        font-size: 12px;
        font-family: "Arial", sans-serif;
        border-bottom: 1px solid #ddd;
    }

    .leaderboard-table tbody tr:nth-child(even) {
        background-color: #f9f9f9;
    }

    .leaderboard-table tbody tr:hover {
        background-color: #e6e6e6;
    }

    .nerd h1,
    .rookie h1 {
        font-family: vivaldi;
        font-size: 2em;
        letter-spacing: 1px;
    }
</style>
{% endblock style %}

{% block content %}
{% include '_navbar.html' %}
<section>
    <main>
        <nav>
            {% if request.user.is_authenticated %}
            <h1 style="width: 100%; margin-left: 20px;"><a href="{% url 'home_page' %}">{{ request.user.first_name }}'s Dashboard</a></h1>
            {% else %}
            <h1><a href="{% url 'home_page' %}">Quizzer</a></h1>
            {% endif %}
            <div class="nav-menu">
                <!-- <div class="language">
                    <i class="fa fa-globe" aria-hidden="true"></i>
                    <select name="lang" id="lang">
                        <option value="English">EN - English</option>
                        <option value="French">FR - French</option>
                    </select>
                </div> -->
                <ul>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'quiz:messages' %}"><i class="fa fa-envelope"></i></a></li>
                    <li><a href="{% url 'quiz:announcements' %}"><i class="fa fa-bell"></i></a></li>
                    <li style="color: black;"><i class="fa fa-copyright"></i> <b>{{ quiz_profile.total_score_annotation }}</b></li>
                    <li><a href="{% url 'quiz:profile' %}" class="profile_name">{{ request.user.first_name|slice:":1" }}</a></li>
                    {% else %}
                    <li><a href="{% url 'quiz:login' %}" class="login">Login</a></li>
                    <li><a href="{% url 'quiz:signup' %}" class="login">Signup</a></li>
                    {% endif %}
                </ul>
            </div>
            <i class="fa fa-bars"></i>
            <i class="fa fa-bars close"></i>

            <div class="responsive-nav-bar">
                <ul>
                    {% if request.user.is_authenticated %}
                    {% url 'home_page' as home_page %}
                    <li class="{% if home_page == request.path %} active {% endif %}">
                        <a href="{{ home_page }}" title="Home">
                            Home
                        </a>
                    </li>

                    {% url 'quiz:category' as category %}
                    <li class="{% if category == request.path %} active {% endif %}">
                        <a href="{{category}}" title="Quiz">
                            Quiz
                        </a>
                    </li>

                    {% url 'quiz:messages' as messages %}
                    <li class="{% if messages == request.path %} active {% endif %}">
                        <a href="{{ messages }}" title="Messages">
                            Messages
                        </a>
                    </li>

                    {% url 'quiz:announcements' as announcements %}
                    <li class="{% if announcements == request.path %} active {% endif %}">
                        <a href="{{ announcements }}" title="Announcements">
                            Announcements
                        </a>
                    </li>
                    <div class="language">
                        <i class="fa fa-globe" aria-hidden="true"></i>
                        <select name="lang" id="lang">
                            <option value="English">EN - English</option>
                            <option value="French">FR - French</option>
                        </select>
                    </div>
                    <li style="color: black;">Total: 0.00</li>
                    <li><a href="{% url 'quiz:profile' %}">Profile</a></li>
                    <li><a href="{% url 'account_logout' %}" class="login">Log Out</a></li>
                    {% else %}
                    <li class="{% if home_page == request.path %} active {% endif %}"><a href="{{ home_page }}">Home</a></li>
                    {% url 'about_page' as about_page %}
                    <li class="{% if about_page == request.path %} active {% endif %}"><a href="{{ about_page }}">About</a></li>
                    <li><a href="">FAQs</a></li>
                    {% url 'contact_page' as contact_page %}
                    <li class="{% if contact_page == request.path %} active {% endif %}"><a href="{{ contact_page }}">Contact</a></li>
                    <div class="language">
                        <i class="fa fa-globe" aria-hidden="true"></i>
                        <select name="lang" id="lang">
                            <option value="English">EN - English</option>
                            <option value="French">FR - French</option>
                        </select>
                    </div>
                    <li><a href="{% url 'quiz:login' %}" class="login">Login</a></li>
                    <li><a href="{% url 'quiz:signup' %}" class="login">Signup</a></li>
                    {% endif %}
                    {% url 'home_page' as home_page %}
                </ul>
            </div>
        </nav>

        <div class="content-body">
            {% if user.is_authenticated %}
            <div class="content">
                <div class="top-box">
                    <div class="content-item">
                        <div class="main-item">
                            <div class="ttt">
                                <h4>Quiz Played</h4>
                                <h3>0</h3>
                            </div>
                            <div class="box-content">
                                <i class="fa fa-award"></i>
                            </div>
                        </div>
                        <div class="go-to-page">
                            <span><a href="{% url 'quiz:quiz_taken' %}">More info <i class="fa fa-chevron-right"></i></a></span>
                        </div>
                    </div>
                    <div class="content-item">
                        <div class="main-item">
                            <div class="ttt">
                                <h4>Quiz Created</h4>
                                <h3>{{ total_quiz_created_by_user }}</h3>
                            </div>
                            <div class="box-content">
                                <i class="fa fa-wrench"></i>
                            </div>
                        </div>
                        <div class="go-to-page">
                            <a href="{% url 'quiz:quiz_created' %}"><span>More info</span> <i class="fa fa-chevron-right"></i></a>
                        </div>
                    </div>
                    <div class="content-item">
                        <div class="main-item">
                            <div class="ttt">
                                <h4>Analytics</h4>
                                <h3>view analytics</h3>
                            </div>
                            <div class="box-content">
                                <i class="fa fa-chart-bar"></i>
                            </div>
                        </div>
                        <div class="go-to-page">
                            <span><a href="{% url 'quiz:quiz_analytics' %}">More info <i class="fa fa-chevron-right"></i></a></span>
                        </div>
                    </div>
                    <div class="content-item">
                        <div class="main-item">
                            <div class="ttt">
                                <h4>Message(s)</h4>
                                <h3>{{ total_messages }}</h3>
                            </div>
                            <div class="box-content">
                                <i class="fa fa-comments"></i>
                            </div>
                        </div>
                        <div class="go-to-page">
                            <span><a href="{% url 'quiz:messages' %}">More info <i class="fa fa-chevron-right"></i></a></span>
                        </div>
                    </div>
                </div>

                <div class="bottom-content">

                    <div class="chart">
                        {% if is_high_score %}
                        <div class="nerd">
                            <img src="{% static 'assets/img/Picture_2-removebg-preview.png' %}" alt="" class="badges" width="300">
                            <h1>Nerd</h1>
                        </div>
                        {% else %}
                        <div class="rookie">
                            <img src="{% static 'assets/img/retro-rookie-magenta-badge-picture_csp56967779-removebg-preview.png' %}" alt="" class="badges" width="300">
                            <h1>Rookie</h1>
                        </div>
                        {% endif %}
                    </div>

                    <div class="quiz-appearance">
                        <h2>Leader Board</h2>
                        <table class="leaderboard-table">
                            <thead>
                                <tr>
                                    <th>Rank</th>
                                    <th>User</th>
                                    <th>Total Score</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for profile in quiz_profiles %}
                                {% if profile.user.is_superuser %}
                                {% else %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ profile.user.first_name }} {{ profile.user.last_name }}</td>
                                    <td>{{ profile.total_score }}</td>
                                </tr>
                                {% endif %}
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>
        {% else %}
        <div class="home-content">
            <div class="text-container">
                <h1>Unlock New Badges <br>to Win Amazing NFTS</h1>
                <a href="{% url 'quiz:signup' %}">Join Now</a>
            </div>

            <div class="img-div swiper img-div-slider">
                <div class="swiper-wrapper">

                    <div class="swiper-slide">
                        <div class="img-item">
                            <img src="{% static 'assets/img/NFT4QUIZedit2.png' %}" alt="" class="nft">
                        </div>
                    </div>

                    <div class="swiper-slide">
                        <div class="img-item">
                            <img src="{% static 'assets/img/NFT4QUIZedit2.png' %}" alt="" class="nft">
                        </div>
                    </div>

                    <div class="swiper-slide">
                        <div class="img-item">
                            <img src="{% static 'assets/img/NFT4QUIZedit2.png' %}" alt="" class="nft">
                        </div>
                    </div>

                    <div class="swiper-slide">
                        <div class="img-item">
                            <img src="{% static 'assets/img/NFT4QUIZedit2.png' %}" alt="" class="nft">
                        </div>
                    </div>

                    <div class="swiper-slide">
                        <div class="img-item">
                            <img src="{% static 'assets/img/NFT4QUIZedit2.png' %}" alt="" class="nft">
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {% endif %}
        </div>
    </main>
</section>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

{% endblock content %}
{% block javascript %}

{% endblock javascript %}

templates/leaderboard.html
{% extends '_base.html' %}
{% load static %}
{% block title %}Leaderboard{% endblock title %}

{% block style %}
<style>
    .container {
        width: 30%;
        margin: 5rem auto;
    }

    h1 {
        text-align: center;
        border-bottom: 3px solid #3B0A6B;
    }

    table {
        width: 100%;
        border-collapse: collapse;
        text-align: center;
    }

    td {
        padding: 10px;
        border-bottom: 1px solid #3B0A6B;
    }

    th {
        font-size: 20px;
        font-weight: 800;
        background-color: #3B0A6B;
        color: white;
        padding: 20px;
        font-family: fira sans;
    }
</style>
{% endblock style %}


{% block content %}
<div class="container">
    <h1><span><i class="bi bi-trophy" aria-hidden="true"></i> TOP {{ total_count }} PLAYERS <i class="bi bi-trophy" aria-hidden="true"></i></span></h1>
    <table>
        <thead>
            <tr>
                <th>Position</th>
                <th>Username</th>
                <th>Score</th>
            </tr>
        </thead>
        <tbody>
            {% for quiz_profile in top_quiz_profiles %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ quiz_profile.user.username }}</td>
                <td>{{ quiz_profile.total_score }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}